name: Continuous Deployment

on:
  release:
    types: [ published ]
    
jobs:
  powershell_gallery:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build -c Release -o .\__publish__
        
      - name: Publish
        run: |
          Publish-Module -Path .\__publish__\Avanti.PowerShellSDK.dll -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
        shell: pwsh
